### ISSUE TITLE
Sorting in Windows

### ISSUE THREAD

**Issue by caufieldjh** [AnacletoLAB/ensmallen#103]
This is a known issue, but one I just encountered:

> from ensmallen_graph.datasets.linqs import Cora
> cora = Cora()
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "C:\Users\JHCaufield\anaconda3\lib\site-packages\ensmallen_graph\datasets\linqs\cora.py", line 109, in Cora
>     return AutomaticallyRetrievedGraph(
>   File "C:\Users\JHCaufield\anaconda3\lib\site-packages\ensmallen_graph\datasets\automatic_graph_retrieval.py", line 85, in __init__
>     raise ValueError(
> ValueError: Currently preprocessing to optimal edge list is not supported on Windows because the sorting step is based upon the `sort` command, which is only available to our knowledge on Linux and macOS systems.
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> NameError: name 'cora' is not defined

There is indeed a `sort` in Windows and I believe its behavior is _mostly_ the same as Linux/MacOS ... but likely not completely identical.
Any way to make this fail more gracefully, or an option to skip the preprocessing?

**Comment by LucaCappelletti94** [comment]
Preprocessing is now automatically disabled in windows. In the depths of time, we will look into how to make use of the Windows APIs (and therefore get a significantly faster load time on Windows), but as I do not have a windows computer close by nor have I ever worked on one hopefully it will no be a problem to most people.
