### ISSUE TITLE
KG-OBO download links are broken

### ISSUE THREAD

**Issue by caufieldjh** [AnacletoLAB/ensmallen#126]
This is likely due to something I changed, but the links to KG-OBO graphs are broken. This is due to the filename changing - in the json definitions ensmallen uses, they look like:
`https://kg-hub.berkeleybop.io/kg-obo/bfo/2019-08-26/bfo.tar.gz`
but the graph files are currently at something more like:
`https://kg-hub.berkeleybop.io/kg-obo/bfo/2019-08-26/bfo_kgx_tsv.tar.gz`

**Comment by LucaCappelletti94** [comment]
Closing this issue as the aforementioned errors are fixed.
