### ISSUE TITLE
Ensmallen version 0.7.0.dev5 core dumping

### ISSUE THREAD

**Issue by justaddcoffee** [AnacletoLAB/ensmallen#135]
To reproduce (possibly might need to be on a machine without AVX):
```
git clone https://github.com/Knowledge-Graph-Hub/kg-obo
git checkout origin/test_ensmallen_070_run_jenkins
/usr/bin/python3.8 -m venv venv
python3 venv/bin/activate
./venv/bin/pip install pathlib
 ./venv/bin/pip install .
python3 run.py --s3_test --bucket fake_bucket --no_dl_progress --get_only bfo
```

Output:

```
Found existing contents at kg-obo/bfo/2019-08-26: ['kg-obo/bfo/2019-08-26/version/']
Found existing contents at kg-obo/bfo: ['kg-obo/bfo/version/']
INFO:kg-obo:Mock created index for bfo and 2019-08-26
processing ontologies: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:09<00:00,  9.52s/it]
INFO:kg-obo:Successfully transformed 1 without errors: ['bfo']
INFO:kg-obo:All available transforms, including old versions (1): ['bfo']
Found existing contents at kg-obo: ['kg-obo/test_obo/', 'kg-obo/test_obo_2/', 'kg-obo/test_obo_2/test_obo_2_version_1/']
Looking for kg-obo/test_obo/index.html
Could not find kg-obo/test_obo/index.html - will not write link
Looking for kg-obo/test_obo_2/index.html
Found kg-obo/test_obo_2/index.html
INFO:kg-obo:Mock updated root index at kg-obo
Mock updated root index at kg-obo
INFO:kg-obo:Removed local data from data.
Testing S3 only - mock checking lock status.
Operation completed without errors (not counting any OBO-specific errors).
Generating reports...
/home/jenkinsuser/test_error/kg-obo/venv/lib/python3.8/site-packages/ensmallen/__init__.py:19: UserWarning: On the current machine, the flags '{'avx2', 'bmi1', 'avx', 'sse4a', 'bmi2'}' are not available.
The library will use a slower but more compatible version.
  warnings.warn(
Illegal instruction (core dumped)
```

**Comment by justaddcoffee** [comment]
Flags from `/proc/cpuinfo`:

```
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 popcnt lahf_lm epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid dtherm ida arat flush_l1d
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
```

**Comment by caufieldjh** [comment]
@kltm in talking with @LucaCappelletti94 and @zommiommy about this issue we've concluded that it may require more time and effort to support non-AVX architectures (i.e., the build server we're using) than to switch it out with something that has those instructions. Do we still have the option to do a hardware change?

**Comment by kltm** [comment]
@caufieldjh I'm probably a little out of the loop, but switching to a "new" machine on some timeline is a possibility.
IIRC, the conversation on whether to 1) find a new physical host, 2) keep the head and do the compute remotely, or 3) go completely remote was still unsettled. I'm guessing that this is the 4th option--muddling through with what you have--dropping off
Another question here is that all of the above require different amounts of effort to accomplish; what would the time bounds on this be? Essentially, the more physical hardware support needed, likely the more time I'd need to spend; the more remote and software work needed, the more somebody else would need to spend in setup. With the end of the year here, I'm pretty pinned down myself at the moment.

**Comment by justaddcoffee** [comment]
@kltm adding to what @caufieldjh said - one easy fix here (for the kg-obo use case here at least) might be to drop in a newer CPU to that machine, one that supports AVX/AVX2 instruction. Shouldn't be more than $100 - $200 or so (@zommiommy which one might work?)

**Comment by kltm** [comment]
@justaddcoffee You beat me :)
I had a rather longer response basically saying it would 1) be more time or money efficient to activate/repurpose one of our current machines (or frankly buying a new one) and 2) a huge PITA (that I would help somebody with but not sign up for myself).

**Comment by caufieldjh** [comment]
> ...what would the time bounds on this be? Essentially, the more physical hardware support needed, likely the more time I'd need to spend; the more remote and software work needed, the more somebody else would need to spend in setup. With the end of the year here, I'm pretty pinned down myself at the moment.

Certainly not the most urgent task since we have backup options including the remote compute. I don't think we're quite ready to shift the entire build pathway to cloud yet but do want to automate our builds as much as we can. Let's take another look in January if possible; it sounds like most machines with a CPU vintage of at least 2015 should do what we need.

**Comment by caufieldjh** [comment]
Thanks, Tommy - I like the idea of having a gcloud-optimized package too.
