### ISSUE TITLE
graph module compiling error on macOS 

### ISSUE THREAD

**Issue by jianshu93** [AnacletoLAB/ensmallen#138]
Hello Team,

Python install succeeds but seperate compiling in the graph module fails:

error: cannot find macro `asm` in this scope
  --> /Users/jianshuzhao/.cargo/git/checkouts/vec_rand-0be24989d24c2226/43472c1/src/xorshift/src/xorshift_avx_ss8.rs:30:9
   |
30 |         asm!(
   |         ^^^
   |
   = note: consider importing one of these items:
           std::arch::asm
           core::arch::asm

error: cannot find macro `asm` in this scope
  --> /Users/jianshuzhao/.cargo/git/checkouts/vec_rand-0be24989d24c2226/43472c1/src/xorshift/src/xorshift_avx_ss4.rs:27:9
   |
27 |         asm!(
   |         ^^^
   |
   = note: consider importing one of these items:
           std::arch::asm
           core::arch::asm

error: cannot find macro `asm` in this scope
  --> /Users/jianshuzhao/.cargo/git/checkouts/vec_rand-0be24989d24c2226/43472c1/src/xorshift/src/xorshift_avx.rs:22:9
   |
22 |         asm!(
   |         ^^^
   |
   = note: consider importing one of these items:
           std::arch::asm
           core::arch::asm

error: cannot find macro `asm` in this scope
  --> /Users/jianshuzhao/.cargo/git/checkouts/vec_rand-0be24989d24c2226/43472c1/src/xorshiro256plus/src/xorshiro256plus_avx_ss4.rs:35:9
   |
35 |         asm!(
   |         ^^^
   |
   = note: consider importing one of these items:
           std::arch::asm
           core::arch::asm

error: cannot find macro `asm` in this scope
  --> /Users/jianshuzhao/.cargo/git/checkouts/vec_rand-0be24989d24c2226/43472c1/src/xorshiro256plus/src/xorshiro256plus_avx.rs:21:9
   |
21 |         asm!(
   |         ^^^
   |
   = note: consider importing one of these items:
           std::arch::asm
           core::arch::asm

error: could not compile `xorshift` due to 3 previous errors
warning: build failed, waiting for other jobs to finish...
error: build failed
/bin/sh: line 9: grcov: command not found
Jianshus-MBP:node2vec-rs jianshuzhao$ The file /Users/jianshuzhao/Github/node2vec-rs/target/debug/coverage/src/index.html does not exist.

Any idea why, it seems the std:asm is not used correctly

Thanks,

Jianshu

**Comment by zommiommy** [comment]
I'm looking into it

**Comment by LucaCappelletti94** [comment]
What version of rust are you using?

**Comment by jianshu93** [comment]
1.59

**Comment by zommiommy** [comment]
Ok, it should be fixed. One of our dependencies used the `asm` feature which was ported to stable in the latest versions of rust nightly. If you run a `cargo update` now it should build.

Sorry for the delay but covid is taking a toll on us, our build process is not trivial so if you need help ping me. A draft on how our compilation process works can be found in the `CONTRIBUTING.md` file on the root of the repository.

**Comment by jianshu93** [comment]
Many Thank!

[NodeSketch](https://dl.acm.org/doi/abs/10.1145/3292500.3330951?casa_token=dcPyDzUwvTIAAAAA:FVRteDcO5j4ytGhVH_J3jiD53iR_9STPDYicAMHSGp3HL-WbTJHyVYHZbjruKTzLaXebEYnDa9tL) is even faster than any other random walk based methods. The new implementation is here: https://github.com/jean-pierreBoth/graphembed

There is no detailed usage page yet but the nodesketch.rs seems very clear. Any interest to implement it?

Thanks,

Jianshu

**Comment by jianshu93** [comment]
Hello, the ASM problem is solved but there is a new bug when compiling under graph directory:



  Downloaded crossbeam-queue v0.3.4
  Downloaded serde_json v1.0.79
  Downloaded nix v0.22.3
  Downloaded counter v0.5.3
  Downloaded cc v1.0.73
  Downloaded libc v0.2.119
  Downloaded 6 crates (1031.7 KB) in 2.31s
   Compiling autocfg v1.1.0
   Compiling cfg-if v1.0.0
   Compiling libc v0.2.119
   Compiling proc-macro2 v1.0.36
   Compiling syn v1.0.86
   Compiling memchr v2.4.1
   Compiling unicode-xid v0.2.2
   Compiling lazy_static v1.4.0
   Compiling crossbeam-utils v0.8.7
   Compiling crossbeam-epoch v0.9.7
   Compiling getrandom v0.1.16
   Compiling scopeguard v1.1.0
   Compiling version_check v0.1.5
   Compiling rayon-core v1.9.1
   Compiling tinyvec_macros v0.1.0
   Compiling log v0.4.14
   Compiling matches v0.1.9
   Compiling either v1.6.1
   Compiling regex-syntax v0.6.25
   Compiling serde v1.0.136
   Compiling unicode-bidi v0.3.7
   Compiling radium v0.6.2
   Compiling serde_derive v1.0.136
   Compiling serde_json v1.0.79
   Compiling bytes v0.5.6
   Compiling v_escape v0.16.1
   Compiling percent-encoding v2.1.0
   Compiling crossbeam-queue v0.3.4
   Compiling ppv-lite86 v0.2.16
   Compiling v_htmlescape v0.13.1
   Compiling cc v1.0.73
   Compiling once_cell v1.9.0
   Compiling hashbrown v0.11.2
   Compiling quick-error v1.2.3
   Compiling ryu v1.0.9
   Compiling tap v1.0.1
   Compiling itoa v1.0.1
   Compiling xorshiro256plus v0.1.0 (https://github.com/zommiommy/vec_rand?branch=master#353234de)
   Compiling funty v1.2.0
   Compiling byteorder v1.4.3
   Compiling bitflags v1.3.2
   Compiling linked-hash-map v0.5.4
   Compiling termcolor v1.1.2
   Compiling cumsum_f64 v0.1.0 (https://github.com/zommiommy/vec_rand?branch=master#353234de)
   Compiling cumsum_f32 v0.1.0 (https://github.com/zommiommy/vec_rand?branch=master#353234de)
   Compiling number_prefix v0.4.0
   Compiling xorshift v0.1.0 (https://github.com/zommiommy/vec_rand?branch=master#353234de)
   Compiling is_sorted v0.1.1
   Compiling atomic_float v0.1.0
   Compiling iter-set v2.0.2
   Compiling glob v0.3.0
   Compiling permutation v0.2.5
   Compiling tags v0.1.0 (/Users/jianshuzhao/Github/node2vec-rs/graph/tags)
   Compiling atoi_radix10 v0.0.1 (https://github.com/gilescope/atoi_radix10#e0bc6511)
   Compiling tinyvec v1.5.1
   Compiling memoffset v0.6.5
   Compiling rayon v1.5.1
   Compiling num-traits v0.2.14
   Compiling indexmap v1.8.0
   Compiling itertools v0.10.3
   Compiling nom v4.2.3
   Compiling form_urlencoded v1.0.1
   Compiling buf-min v0.6.1
   Compiling humantime v1.3.0
   Compiling wyz v0.4.0
   Compiling linked_hash_set v0.1.4
   Compiling roaring v0.6.1 (https://github.com/zommiommy/roaring-rs?branch=master#4a7e9c90)
   Compiling graph v0.6.0 (/Users/jianshuzhao/Github/node2vec-rs/graph)
   Compiling unicode-normalization v0.1.19
   Compiling crossbeam-channel v0.5.2
   Compiling quote v1.0.15
   Compiling aho-corasick v0.7.18
   Compiling num_cpus v1.13.1
   Compiling terminal_size v0.1.17
   Compiling atty v0.2.14
   Compiling bitvec v0.22.3
   Compiling nix v0.22.3
   Compiling rand_core v0.5.1
   Compiling console v0.15.0
   Compiling idna v0.2.3
   Compiling regex v1.5.4
   Compiling keyed_priority_queue v0.3.2
   Compiling counter v0.5.3
   Compiling crossbeam-deque v0.8.1
   Compiling rand_chacha v0.2.2
   Compiling rand_pcg v0.2.1
   Compiling url v2.2.2
   Compiling crossbeam v0.8.1
   Compiling env_logger v0.7.1
   Compiling rand v0.7.3
   Compiling validator_types v0.14.0
   Compiling vec_rand v0.1.0 (https://github.com/zommiommy/vec_rand?branch=master#353234de)
   Compiling elias_fano_rust v0.1.1
   Compiling indicatif v0.16.2
   Compiling v_escape_derive v0.8.5
   Compiling derive_arbitrary v0.4.7
   Compiling derive-getters v0.1.1
   Compiling arbitrary v0.4.7
   Compiling validator v0.14.0
error[E0277]: cannot add-assign `&usize` to `&usize`
   --> src/holdouts.rs:147:48
    |
147 |             let complete_edges_number: EdgeT = Counter::init(node_components.clone())
    |                                                ^^^^^^^^^^^^^ no implementation for `&usize += &usize`
    |
    = help: the trait `AddAssign` is not implemented for `&usize`
note: required by a bound in `Counter::<T, N>::init`
   --> /Users/jianshuzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/counter-0.5.3/src/lib.rs:178:21
    |
178 |     N: PartialOrd + AddAssign + SubAssign + Zero + One,
    |                     ^^^^^^^^^ required by this bound in `Counter::<T, N>::init`

error[E0277]: cannot subtract-assign `&usize` from `&usize`
   --> src/holdouts.rs:147:48
    |
147 |             let complete_edges_number: EdgeT = Counter::init(node_components.clone())
    |                                                ^^^^^^^^^^^^^ no implementation for `&usize -= &usize`
    |
    = help: the trait `SubAssign` is not implemented for `&usize`
note: required by a bound in `Counter::<T, N>::init`
   --> /Users/jianshuzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/counter-0.5.3/src/lib.rs:178:33
    |
178 |     N: PartialOrd + AddAssign + SubAssign + Zero + One,
    |                                 ^^^^^^^^^ required by this bound in `Counter::<T, N>::init`

error[E0277]: the trait bound `&usize: num_traits::Zero` is not satisfied
   --> src/holdouts.rs:147:48
    |
147 |             let complete_edges_number: EdgeT = Counter::init(node_components.clone())
    |                                                ^^^^^^^^^^^^^ the trait `num_traits::Zero` is not implemented for `&usize`
    |
    = help: the following implementations were found:
              <usize as num_traits::Zero>
note: required by a bound in `Counter::<T, N>::init`
   --> /Users/jianshuzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/counter-0.5.3/src/lib.rs:178:45
    |
178 |     N: PartialOrd + AddAssign + SubAssign + Zero + One,
    |                                             ^^^^ required by this bound in `Counter::<T, N>::init`

error[E0277]: the trait bound `&usize: One` is not satisfied
   --> src/holdouts.rs:147:48
    |
147 |             let complete_edges_number: EdgeT = Counter::init(node_components.clone())
    |                                                ^^^^^^^^^^^^^ the trait `One` is not implemented for `&usize`
    |
    = help: the following implementations were found:
              <usize as One>
note: required by a bound in `Counter::<T, N>::init`
   --> /Users/jianshuzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/counter-0.5.3/src/lib.rs:178:52
    |
178 |     N: PartialOrd + AddAssign + SubAssign + Zero + One,
    |                                                    ^^^ required by this bound in `Counter::<T, N>::init`

error[E0308]: mismatched types
  --> src/tfidf.rs:74:36
   |
74 |                 .map(|(&word_name, &word_count)| {
   |                                    ^^^^^^^^^^^- expected due to this
   |                                    |
   |                                    expected `usize`, found reference
   |                                    help: you can probably remove the explicit borrow: `word_count`
   |
   = note:   expected type `usize`
           found reference `&_`

error[E0308]: mismatched types
  --> src/tfidf.rs:76:51
   |
20 | pub fn okapi_bm25_tfidf<T1: Eq + Hash + Send + Sync + Clone + Copy + Eq>(
   |                         -- this type parameter
...
76 |                     let word_id = *vocabulary.get(word_name).unwrap();
   |                                                   ^^^^^^^^^
   |                                                   |
   |                                                   expected reference, found type parameter `T1`
   |                                                   help: consider borrowing here: `&word_name`
   |
   = note:   expected reference `&_`
           found type parameter `T1`

error[E0614]: type `T1` cannot be dereferenced
  --> src/tfidf.rs:79:25
   |
79 |                         *word_name,
   |                         ^^^^^^^^^^

Some errors have detailed explanations: E0277, E0308, E0614.
For more information about an error, try `rustc --explain E0277`.
error: could not compile `graph` due to 7 previous errors



Any idea,



And also on MacOS ARM64 (M1 chip):


   Compiling xorshift v0.1.0 (https://github.com/zommiommy/vec_rand?branch=master#353234de)
error[E0635]: unknown feature `stdarch`
 --> /Users/jianshuzhao/.cargo/git/checkouts/vec_rand-0be24989d24c2226/353234d/src/cumsum_f32/src/lib.rs:1:12
  |
1 | #![feature(stdarch)]
  |            ^^^^^^^

   Compiling funty v1.2.0
For more information about this error, try `rustc --explain E0635`.
error: could not compile `cumsum_f32` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed



It seem on ARM the stdarch feature should not be used.
Thanks,


Jianshu

**Comment by zommiommy** [comment]
I tried to fix it, run a `cargo update` in the `graph` folder of the repository and try compiling again. 

Thank you for opening this issue

**Comment by zommiommy** [comment]
> There is no detailed usage page yet but the nodesketch.rs seems very clear. Any interest to implement it?

Due to COVID we are just maintaining the repo, as you might have noticed and I apologize for the huge delays, so we don't plan to add any new features in the near future. But it's for sure interesting and we will consider it in the future, thank you!

**Comment by LucaCappelletti94** [comment]
Hello @jianshu93, this issue should no longer exist in the updated builds of ensmallen. Do try to install the library by running `pip install grape`. Do feel free to reopen the issue if there are still problems.
