### ISSUE TITLE
PyPI source code link broken

### ISSUE THREAD

**Issue by RemyLau** [AnacletoLAB/ensmallen#177]
Currently (version 0.8.24), the source code link on [PyPI](https://pypi.org/project/ensmallen/0.8.24/) is https://github.com/LucaCappelletti94/ensmallen, which do not exist anymore

**Comment by LucaCappelletti94** [comment]
Thank you for reporting this! It was still pointing to my account, I thought it would redirect. I will update it asap.

**Comment by LucaCappelletti94** [comment]
I have updated the metadata. In the next version it should be updated. Thanks again!

**Comment by RemyLau** [comment]
Wonderful!
