### ISSUE TITLE
Problems installing the latest version on win11

### ISSUE THREAD

**Issue by jonsenhb** [AnacletoLAB/ensmallen#225]
I want to install the latest ensmallen library on win11 system, but the installation is unsuccessful. I can only install the old version through pip install.

**Comment by jonsenhb** [comment]
ERROR: Could not find a version that satisfies the requirement ensmallen==0.8.84 (from versions: 0.0.1, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.6.6, 0.7.0.dev5, 0.7.0.dev6, 0.7.0.dev7, 0.7.0.dev8, 0.7.0.dev9, 0.7.0.dev19, 0.8.0, 0.8.1, 0.8.2, 0.8.25, 0.8.26, 0.8.27, 0.8.28, 0.8.29, 0.8.36, 0.8.42, 0.8.43, 0.8.44)
ERROR: No matching distribution found for ensmallen==0.8.84

**Comment by LucaCappelletti94** [comment]
Hi @jonsenhb, the Windows system has problems handling the compilation of the more recent versions of Ensmallen. You can learn more about this here: https://github.com/AnacletoLAB/grape/issues/49

I suggest you try working on a system that can compile Ensmallen, such as Linux or MacOS, or web services such as COLAB.

Hopefully, at some point, we will be able to return to make available also the Windows version but it does not look likely in the short term.

**Comment by jonsenhb** [comment]
> Hi @jonsenhb, the Windows system has problems handling the compilation of the more recent versions of Ensmallen. You can learn more about this here: [AnacletoLAB/grape#49](https://github.com/AnacletoLAB/grape/issues/49)
> 
> I suggest you try working on a system that can compile Ensmallen, such as Linux or MacOS, or web services such as COLAB.
> 
> Hopefully, at some point, we will be able to return to make available also the Windows version but it does not look likely in the short term.

Thank you very much for your answer
